package eu.datex2.wsdl.clientpull._2_0;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-09-15T19:38:22.957+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://datex2.eu/wsdl/clientPull/2_0", name = "clientPullInterface")
@XmlSeeAlso({eu.datex2.schema._2._2_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClientPullInterface {

    @WebResult(name = "d2LogicalModel", targetNamespace = "http://datex2.eu/schema/2/2_0", partName = "body")
    @WebMethod(action = "http://datex2.eu/wsdl/clientPull/2_0/getDatex2Data")
    public eu.datex2.schema._2._2_0.D2LogicalModel getDatex2Data();
}
